name: build

on:
  push:
  repository_dispatch:
    types: [nightly]

env:
  HVCC_COMMIT_HASH: "${{ github.event.client_payload.nightly && github.event.client_payload.branch || '8f754b10abaec5308e1700e414461b6c4a5ff35a' }}"
  CACHE_VERSION: 2
  DEBIAN_FRONTEND: noninteractive
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-riscv64, linux-x86_64]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          hvcc: True

  windows:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          hvcc: True

  macos:
    strategy:
      matrix:
        target: [macos-intel, macos-universal]
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: innodatalabs/action-pip-conf@1.0.0
        with:
            pip-conf: "[global]\nbreak-system-packages = true"

      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          hvcc: True

  pluginval:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: pluginval
          hvcc: True

  source:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: source
